In [290]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split

df = pd.read_csv('winequality-red-mod.csv')

In [291]:
df

,id,fixed acidity,volatile acidity,citric acid,residual sugar,flavonoids,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,country,quality
0,1,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,UK,5
1,2,7.8,0.880,0.00,2.6,0.7540,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Italy,5
2,3,7.8,0.760,0.04,2.3,0.6880,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Italy,5
3,4,11.2,0.280,0.56,1.9,0.4590,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Spain,6
4,5,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,UK,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,1502,6.4,0.310,0.09,1.4,0.4230,0.066,15.0,28.0,0.99459,3.42,0.70,10.0,UK,7
1502,1503,7.0,0.430,0.02,1.9,0.5290,0.080,15.0,28.0,0.99492,3.35,0.81,10.6,Spain,6
1503,1504,7.7,0.540,0.26,1.9,0.6070,0.089,23.0,147.0,0.99636,3.26,0.59,9.7,UK,5
1504,1505,6.9,0.740,0.03,2.3,0.4920,0.054,7.0,16.0,0.99508,3.45,0.63,11.5,UK,6
1505,1506,6.6,0.895,0.04,2.3,0.6085,0.068,7.0,13.0,0.99582,3.53,0.58,10.8,Spain,6

In [292]:
df = df.drop(columns = 'id', axis = 1)

In [293]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,flavonoids,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,country,quality
0,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,UK,5
1,7.8,0.880,0.00,2.6,0.7540,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Italy,5
2,7.8,0.760,0.04,2.3,0.6880,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Italy,5
3,11.2,0.280,0.56,1.9,0.4590,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Spain,6
4,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,UK,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,6.4,0.310,0.09,1.4,0.4230,0.066,15.0,28.0,0.99459,3.42,0.70,10.0,UK,7
1502,7.0,0.430,0.02,1.9,0.5290,0.080,15.0,28.0,0.99492,3.35,0.81,10.6,Spain,6
1503,7.7,0.540,0.26,1.9,0.6070,0.089,23.0,147.0,0.99636,3.26,0.59,9.7,UK,5
1504,6.9,0.740,0.03,2.3,0.4920,0.054,7.0,16.0,0.99508,3.45,0.63,11.5,UK,6
1505,6.6,0.895,0.04,2.3,0.6085,0.068,7.0,13.0,0.99582,3.53,0.58,10.8,Spain,6

In [294]:
df = pd.get_dummies(df)

In [295]:
df = df.drop(columns = 'country_UK', axis = 1)

In [296]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,flavonoids,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,country_Italy,country_Spain
0,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0,0
1,7.8,0.880,0.00,2.6,0.7540,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1,0
2,7.8,0.760,0.04,2.3,0.6880,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,1,0
3,11.2,0.280,0.56,1.9,0.4590,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0,1
4,7.4,0.700,0.00,1.9,0.5900,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,6.4,0.310,0.09,1.4,0.4230,0.066,15.0,28.0,0.99459,3.42,0.70,10.0,7,0,0
1502,7.0,0.430,0.02,1.9,0.5290,0.080,15.0,28.0,0.99492,3.35,0.81,10.6,6,0,1
1503,7.7,0.540,0.26,1.9,0.6070,0.089,23.0,147.0,0.99636,3.26,0.59,9.7,5,0,0
1504,6.9,0.740,0.03,2.3,0.4920,0.054,7.0,16.0,0.99508,3.45,0.63,11.5,6,0,0
1505,6.6,0.895,0.04,2.3,0.6085,0.068,7.0,13.0,0.99582,3.53,0.58,10.8,6,0,1

In [297]:
df = df.drop([151], axis = 0)
df = df.drop([1081], axis=0)
df = df.drop([1083], axis=0)
df = df.drop([1423],axis=0)
df = df.drop([34],axis=0)
df = df.drop([258],axis=0)
df = df.drop([289],axis=0)
df = df.drop([291],axis=0)
df = df.drop([546],axis=0)
df = df.drop([592],axis=0)
df = df.drop([106],axis=0)
df = df.drop([221],axis=0)
df = df.drop([315],axis=0)
df = df.drop([374],axis=0)
df = df.drop([447],axis=0)
df = df.drop([700],axis=0)
df = df.drop([735],axis=0)
df = df.drop([937],axis=0)
df = df.drop([938],axis=0)
df = df.drop([977],axis=0)
df = df.drop([978],axis=0)
df = df.drop([1249],axis=0)
df = df.drop([86], axis=0)

In [298]:
df = df.sample(frac=1, replace = True, random_state = 1)

In [299]:
feat

,fixed acidity,volatile acidity,citric acid,residual sugar,flavonoids,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,country_Italy,country_Spain
1080,8.6,0.370,0.65,6.4,0.5110,0.080,3.0,8.0,0.99817,3.27,0.58,11.0,0,0
240,8.9,0.635,0.37,1.7,1.5055,0.263,5.0,62.0,0.99710,3.00,1.09,9.3,0,0
1117,7.0,0.690,0.07,2.5,0.6620,0.091,15.0,21.0,0.99572,3.38,0.60,11.3,1,0
920,8.4,0.360,0.32,2.2,0.5130,0.081,32.0,79.0,0.99640,3.30,0.72,11.0,0,1
729,6.4,0.570,0.02,1.8,0.5060,0.067,4.0,11.0,0.99700,3.46,0.68,9.5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233,5.1,0.420,0.00,1.8,0.3460,0.044,18.0,88.0,0.99157,3.68,0.73,13.6,0,1
208,7.8,0.440,0.28,2.7,0.6320,0.100,18.0,95.0,0.99660,3.22,0.67,9.4,1,0
22,7.9,0.430,0.21,1.6,0.6590,0.106,10.0,37.0,0.99660,3.17,0.91,9.5,0,0
145,8.1,0.670,0.55,1.8,0.7860,0.117,32.0,141.0,0.99680,3.17,0.62,9.4,0,0
418,7.0,0.580,0.12,1.9,0.6290,0.091,34.0,124.0,0.99560,3.44,0.48,10.5,0,0

In [300]:
correlationmatrix = df.corr()['quality']

In [301]:
correlationmatrix

fixed acidity           0.123882
volatile acidity       -0.331085
citric acid             0.203128
residual sugar          0.021808
flavonoids             -0.190720
chlorides              -0.084402
free sulfur dioxide    -0.047305
total sulfur dioxide   -0.210109
density                 0.045690
pH                      0.001161
sulphates               0.260759
alcohol                 0.482617
quality                 1.000000
country_Italy          -0.002260
country_Spain           0.019754
Name: quality, dtype: float64

In [302]:
df = df.dropna()

In [303]:
label = df['quality']
feat = df.drop(columns = 'quality', axis = 1)

In [305]:
X_train, X_test, y_train, y_test = train_test_split(feat, label, random_state = 0)

In [306]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics

clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(f'Accuracy: {metrics.accuracy_score(y_test, y_pred)}')

Accuracy: 0.7978436657681941

In [307]:
# let's try Naive Bayes Classifier

from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 

accuracy = gnb.score(X_test, y_test) 
print(accuracy) 

cm = confusion_matrix(y_test, gnb_predictions)

0.5013477088948787

In [308]:
# bad

In [309]:
# let's try SVM

from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 
    
accuracy = svm_model_linear.score(X_test, y_test) 

cm = confusion_matrix(y_test, svm_predictions)

In [310]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, svm_predictions))

0.5956873315363881

In [311]:
# also bad
# decision trees is best for this data set in terms of supervised ML.